/* This file is generated by code_gen.py */
#ifndef __SCHEMA_H__
#define __SCHEMA_H__
	struct mat4 {
		int i;
		int j;
		int val;
	};

	struct mat2 {
		int i;
		int j;
		int val;
	};

	struct mat3 {
		int i;
		int j;
		int val;
	};

	struct mat1 {
		int i;
		int j;
		int val;
	};

#endif
