/*
 * select R.x, R.y, S.z from R, S where R.y = S.y 
 */
SELECT
  TABLEA.ID,
  TABLEA.BEER,
  TABLEB.ID,
  TABLEB.BEER
FROM TABLEA, TABLEB
WHERE TABLEA.BEER = TABLEB.BEER;
--WHERE TABLEA.FACTORY = TABLEB.FACTORY;
--WHERE TABLEA.STYLE = TABLEB.STYLE;
--WHERE TABLEA.ABV = TABLEB.ABV;
