/*
 * select R.x, R.y, S.z from R, S where R.y = S.y 
 * only performs join w/o counting
 */
SELECT
  TABLEA.ID,
  TABLEA.SONG,
  TABLEA.ELAPSE,
  TABLEB.ID,
  TABLEB.SONG,
  TABLEB.ELAPSE
FROM TABLEA, TABLEB
WHERE TABLEA.ALBUM = TABLEB.ALBUM;
--WHERE TABLEA.COPYRIGHT = TABLEB.COPYRIGHT;
--WHERE TABLEA.ARTIST = TABLEB.ARTIST;
--WHERE TABLEA.ELAPSE = TABLEB.ELAPSE;
--WHERE TABLEA.GENRE = TABLEB.GENRE;
--WHERE TABLEA.PRICE = TABLEB.PRICE;
